### ISSUE TITLE
Can‘t find API Token

### ISSUE THREAD

**Issue by derBlitzen** [AdyRock/ady.solarman#1]
Hi there,

Regrettably I cannot find the API token in the Solarman app. Any assistance would be highly appreciated.

Cheers,
-Peter

**Comment by AdyRock** [comment]
How have you installed the app?
When you add a device you should be prompted to login with your Solarman credentials.

**Comment by derBlitzen** [comment]
Yes. But when I try to log on using my Solarman credential, I get the error message **Failed to get station list**.

**Comment by AdyRock** [comment]
As far as I know, the API key I was given should be for the app so it can authentice with user credentials to access their account. 
Could you enable the log (blue tick) in the Configure App screen. Then try adding your device and then go back to the Log and Send it.

**Comment by derBlitzen** [comment]
Already tried that. The log shows only that:

```
* 2022-10-30T13:35:28.789Z
Get Data

* 2022-10-30T13:36:51.358Z
No Data
```

**Comment by AdyRock** [comment]
Forget the last request. It seems I can't add my station either. I will check to see if an error has crept in while adding local support or if it's just Solarman having an issue.

**Comment by bigfib** [comment]
Hi there.
Sorry if these questions are dumb in advance but I'm a beginner here.
I installed the Homey app and added the sofar "station" addon, but when I try to add a device (my sofar me3000sp) it asks me for a user name/password. I've tried my login for Solarman.cn and my login for the inverter (admin/admin) but both are refused with a simple "failed" message. Any ideas? Perhaps I need homey hardware on my network to use these options and the cloud version isn't enough? Many thanks.

**Comment by AdyRock** [comment]
It should work fine with the Homey cloud version, but only for the Solarman cloud device.
You should use you Soalarman cloud user name and password.

**Comment by bigfib** [comment]
Thanks. Just to be clear, I login successfully to home.solarman.cn/login.html with my email address and a password which is what I’m trying here. It’s says “error.”
![E26DF5A0-34BE-432F-AD86-61E954840BC4](https://user-images.githubusercontent.com/127230026/223764210-eb9ed042-6c9a-4a76-bd24-46410c21f60e.png)

**Comment by bigfib** [comment]
![6C5F1F2C-9F19-4AB4-8F81-D91AA755AD18](https://user-images.githubusercontent.com/127230026/223765221-6cb9deb2-4576-4b3f-84d3-c98ff934cf58.jpeg)

**Comment by AdyRock** [comment]
I'm not sure why. I tried on my account and it is logging in fine.
Could you send a diagnostics report from the App page to see if that shows any issues.

**Comment by bigfib** [comment]
Thanks.I’ve done that.01034eb5-0472-489d-a156-06664c085c27Sent from my iPhoneOn 8 Mar 2023, at 17:24, Adrian Rockall ***@***.***> wrote:﻿
I'm not sure why. I tried on my account and it is logging in fine.
Could you send a diagnostics report from the App page to see if that shows any issues.

**Comment by bigfib** [comment]
Thanks
I sent the diagnostics report.
Thanks for all your help.

**Comment by AdyRock** [comment]
Is it working with the latest version?

**Comment by bigfib** [comment]
Hi Andy. Sorry I gave up on Homey and installed Home Assistant with the Joubert integration instead.Thanks anyway though.Best wishes.Nick.Sent from my iPhoneOn 1 Apr 2023, at 22:42, Adrian Rockall ***@***.***> wrote:﻿
Is it working with the latest version?

**Comment by AdyRock** [comment]
Ok, no problem. Hope it goes well.
