### ISSUE TITLE
App update interval

### ISSUE THREAD

**Issue by Arnoud1964** [AdyRock/ady.solarman#11]
Is it possible to increase the update interval by your app of de Solarman cloud data  from 15 to the 5 minute intervals of the Solarman cloud data?

**Comment by AdyRock** [comment]
At the moment I am concerned about hitting the rate limit of API calls allowed on my developer account. I previously made the silly mistake of syncing the history data on the hour, but that meant all the Homeys accessed the API at the same time and subsequently the account was locked. I changed the app to keep it random and got the account reactivated, but I'm concerned it could get locked again. 
Once I get a feel for the number of users I might be able to reduce the time.

**Comment by Arnoud1964** [comment]
OK, thanks for your answer! 
I'll wait patiencely for a increased update frequency....
