### ISSUE TITLE
Failed to get station list

### ISSUE THREAD

**Issue by rvisser88** [AdyRock/ady.solarman#3]
I never come further then this:
![Screenshot_20230324_093432_Homey](https://user-images.githubusercontent.com/51273481/227467395-af9aec23-8602-48a6-b4e5-8d7050cbe6bf.jpg)
Everything works fine in the 'SOLARMAN Smart' app.
I use this tile (also tried all the others):
![Screenshot_20230324_093451_Homey](https://user-images.githubusercontent.com/51273481/227467690-74fc1d3e-6982-46cf-80b7-45a50b944a75.jpg)

**Comment by AdyRock** [comment]
Do you still have the same problem with the latest version?

**Comment by rvisser88** [comment]
Yes, i still have the same problem.
But now it says: 'HTTPS Error: Nothing returned'

I reinstalled the app a couple off times, but it doesn't ask me to re-login. 
Does it remember the login or is it an issue?

**Comment by AdyRock** [comment]
Could you send me a Diagnostics Log from the App so I can check what is happening?

**Comment by rvisser88** [comment]
Done, but log is empty for me

**Comment by AdyRock** [comment]
Could you enable the Log Internet Data option, then try to add your inverter and send the log again.

**Comment by rvisser88** [comment]
Done and tried it a couple of times, but log stays empty.

**Comment by AdyRock** [comment]
That is really strange, I can't understand why the log is empty. 
I will look deeper.

**Comment by rvisser88** [comment]
Also changed my password of Solarman Smart, but doesnt even ask for the new password.

**Comment by rvisser88** [comment]
Dont know what you changed, but now it workes perfect!
Thank you very mucj, keep up the good work!!
