### ISSUE TITLE
Homey bridge problem

### ISSUE THREAD

**Issue by dowidopo** [AdyRock/ady.solarman#5]
Hello, i have problem with the app in homey bridge. There is the red triangle and can not to connect and click on that. If i delete the app and want to add it from web app then it only connecting and then the timeout message show but it did not open any window to log in.
Thank you for help.

![Screenshot_20230401_172325_Homey](https://user-images.githubusercontent.com/116274762/229298670-9882b251-b4c0-4b74-a642-c670a5809354.jpg)

**Comment by AdyRock** [comment]
Could you send a Diagnostics Log please.

**Comment by dowidopo** [comment]
Hello, here is a log 

70e212be-5d2a-4975-a901-bb6c5290042f

**Comment by AdyRock** [comment]
Thanks for the log, it's very helpful. It looks like when I fixed a path problem on Homey 2023, it broke it for Homey cloud.

**Comment by AdyRock** [comment]
New version is live which should fix the crash on Homey.

**Comment by dowidopo** [comment]
Thank you. It's work.
