### ISSUE TITLE
How to connect an Omnik converter under a Solarman account

### ISSUE THREAD

**Issue by Arnoud1964** [AdyRock/ady.solarman#8]
How can I connect an Omnik converter under a Solarman account in this Homey app?

**Comment by AdyRock** [comment]
Have you added the Inverter to Solarman?

**Comment by Arnoud1964** [comment]
Yes, it's connected in the Solarman app

**Comment by AdyRock** [comment]
Ok, you should be able to add the Solarman Station device and it will ask you to login using your Solarman credentials.

**Comment by Arnoud1964** [comment]
OK. thanks my inverter is now connected to my Homey Pro
